# 在配置文件中指定zookeeper的host以及port端口信息
apache:
  zookeeper:
    host: 192.168.170.129
    port: 2181
  hbase:
    address: "192.168.170.129:60000"

# 用于调试hbase进行数据库建表create table时卡顿的问题
logging:
  level:
    org.apache.hadoop.hbase: debug