# 在配置文件中指定zookeeper的host以及port端口信息
apache:
  zookeeper:
    address: 47.101.206.249:2181,47.101.216.12:2181,47.101.204.23:2181

# 用于调试hbase进行数据库建表create table时卡顿的问题
logging:
  level:
    org.apache.hadoop.hbase: debug